/* Continuous geometric landscape. No raster 3D artwork or imported models. */
(()=>{'use strict';const host=document.getElementById('world'),reduced=matchMedia('(prefers-reduced-motion:reduce)');let renderer;
function fallback(){document.body.classList.add('scene-unavailable');host.querySelector('canvas')?.remove()}
if(!window.THREE){fallback();return}try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'})}catch{fallback();return}
renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<760?1.25:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.append(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x080d14,.025);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,160);const world=new THREE.Group();scene.add(world);
scene.add(new THREE.HemisphereLight(0xc9e9ff,0x0d1225,2.3));const key=new THREE.DirectionalLight(0xe7f6ff,4);key.position.set(5,10,5);scene.add(key);const rim=new THREE.DirectionalLight(0x669bd4,4);rim.position.set(-6,2,-6);scene.add(rim);
const ice=new THREE.MeshPhysicalMaterial({color:0xa8c9e6,metalness:.45,roughness:.13,clearcoat:1,clearcoatRoughness:.08});const deep=new THREE.MeshStandardMaterial({color:0x244c6c,metalness:.75,roughness:.3});
const sculpture=new THREE.Group();sculpture.position.set(3,0,0);world.add(sculpture);const crystal=new THREE.Mesh(new THREE.IcosahedronGeometry(2.5,0),ice);crystal.scale.set(1,1.3,1);crystal.rotation.set(.3,.3,.15);sculpture.add(crystal);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(crystal.geometry),new THREE.LineBasicMaterial({color:0xe6f5ff,transparent:true,opacity:.4}));edges.scale.copy(crystal.scale);edges.rotation.copy(crystal.rotation);sculpture.add(edges);
for(let i=0;i<4;i++){const orbit=new THREE.Mesh(new THREE.TorusGeometry(3.4+i*.4,.017,6,110),deep);orbit.rotation.set(.6+i*.5,.2+i*.7,.4);sculpture.add(orbit)}
const field=new THREE.Group();world.add(field);for(let i=0;i<56;i++){const angle=i*2.39996,r=7+(i%13)*1.1;const m=new THREE.Mesh(new THREE.OctahedronGeometry(.3+(i%5)*.18,0),i%3?ice:deep);m.position.set(Math.cos(angle)*r,-3+(i%7)*.6,Math.sin(angle)*r-6);m.scale.y=1+(i%4)*.65;m.rotation.set(i*.4,i*.7,i*.2);field.add(m)}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(140,140),new THREE.MeshStandardMaterial({color:0x101e2d,metalness:.65,roughness:.38}));floor.rotation.x=-Math.PI/2;floor.position.y=-4;world.add(floor);
const dustGeo=new THREE.BufferGeometry(),positions=new Float32Array(240*3);for(let i=0;i<240;i++){positions[i*3]=Math.sin(i*17.31)*35;positions[i*3+1]=Math.cos(i*5.27)*14;positions[i*3+2]=Math.sin(i*2.73)*40}dustGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xb5d4f2,size:.045,transparent:true,opacity:.5}));scene.add(dust);
const ids=['home','work','about','skills','journey','studio','connect'];const stops=[[0,1,12,3,0,0],[8,3,11,1,0,-2],[12,2,2,2,0,-3],[7,5,-7,0,-1,-3],[-5,3,-10,0,0,-2],[-10,1,1,1,0,0],[0,2,12,3,0,0]];let anchors=[],target=0,progress=0,px=0,py=0,raf=0,last=0,elapsed=0;
const isPaused=()=>reduced.matches||document.body.classList.contains('motion-off');
function measure(){anchors=ids.map(id=>document.getElementById(id).offsetTop);renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();scroll();draw()}
function scroll(){const y=scrollY+innerHeight*.2;let index=0;while(index<anchors.length-1&&y>=anchors[index+1])index++;target=index===anchors.length-1?index:index+Math.max(0,Math.min(1,(y-anchors[index])/(anchors[index+1]-anchors[index])));if(isPaused()){progress=target;draw()}else start()}
function draw(){const i=Math.min(stops.length-2,Math.floor(progress)),t=Math.min(1,progress-i),a=stops[i],b=stops[i+1],e=t*t*(3-2*t);const values=a.map((v,k)=>v+(b[k]-v)*e);camera.position.set(values[0]+(isPaused()?0:px*.35),values[1]+(isPaused()?0:py*.2),values[2]);camera.lookAt(values[3],values[4],values[5]);sculpture.rotation.y=elapsed*.055;sculpture.position.y=Math.sin(elapsed*.45)*.12;dust.rotation.y=elapsed*.008;renderer.render(scene,camera)}
function tick(now){raf=0;if(document.hidden)return;const delta=Math.min(.05,(now-last)/1000||.016);last=now;if(!isPaused()){elapsed+=delta;progress+=(target-progress)*Math.min(1,delta*5)}else progress=target;draw();if(!isPaused())raf=requestAnimationFrame(tick)}
function start(){if(!raf&&!document.hidden)raf=requestAnimationFrame(tick)}
addEventListener('scroll',scroll,{passive:true});addEventListener('resize',measure);addEventListener('pointermove',e=>{px=e.clientX/innerWidth-.5;py=.5-e.clientY/innerHeight},{passive:true});document.querySelector('.motion-toggle').addEventListener('click',()=>{if(raf)cancelAnimationFrame(raf);raf=0;progress=target;draw();if(!isPaused())start()});reduced.addEventListener('change',()=>{if(raf)cancelAnimationFrame(raf);raf=0;progress=target;draw();if(!isPaused())start()});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else{last=0;start()}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);fallback()});document.body.classList.add('world-ready');measure();start();window.portfolioScene={get camera(){return camera.position.toArray()},get chapter(){return progress},get frames(){return renderer.info.render.frame}};
})();
